pipeline:
  install:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn

  test:
    image: node:8.6.0
    group: testing
    commands:
      - yarn test

  lint:
    image: node:8.6.0
    group: testing
    commands:
      - yarn lint

  publish:
    image: plugins/ecr
    access_key: AKIAJRDOMRBZSMNHNBEQ
    secret_key: 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
    repo: people22/helloworld
    region: ap-northeast-1
    tags: ${DRONE_COMMIT_SHA:0:8}
