pipeline:
  install:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn

  test:
    image: node:8.6.0
    group: testing
    commands:
      - yarn test
      
  lint:
    image: node:8.6.0
    group: testing
    commands:
      - yarn lint
